name: create tag

on:
  push:
    branches:
      - master
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.TAP_GITHUB_TOKEN }}